### PR TITLE
User Microposts

### PR DESCRIPTION
**Pull request by edenvicary**
Sample App is modelling Twitter like functionality so the core of the app is the ability to create and view the microposts from yourself and others.

### CODE REVIEW

**Comment by felixclack** [comment]
Looks good.

I would prefer not to have empty or unused files getting committed though, eg.  [test/fixtures/microposts.yml](https://github.com/EdenVicary/sample_app/blob/user-microposts/test/fixtures/microposts.yml) & [test/models/micropost_test.rb](https://github.com/EdenVicary/sample_app/blob/user-microposts/test/models/micropost_test.rb).

**Comment by EdenVicary** [comment]
Ok, so @felixclack  would you just leave them out of the commits until you use them? or delete the generated files and recreate them when they are needed?

**Comment by felixclack** [comment]
I'd delete them and recreate when I need them. 



—
Thanks,
Felix

**Comment by EdenVicary** [comment]
@felixclack Enough commits for you? I feel like its really telling the story of the code.

**Comment by EdenVicary** [comment]
How do you like this for a rebase? 25 commits

pick 119988c Add Microposts to DB
s b0aa24b Improve the sample data for the user test
s 4a9b746 Ensure User Id is present
s b65debc Add Validation to content
s baf87f3 Add User to Microposts relationship
s adcd316 Add descending order for microposts
s 80898de Enforse implied deletion in the user > microposts relationship
s 0805129 Show Un styled microposts on user's profile page
s 802a568 Clean Up unused js, css, helpers, controllers and tests
s 1d42eaf Add example microposts to db seed
s 7e6814f Fix destroy user relationship enforcement tests around microposts
s 1eae074 Test profile for microposts on page
s 8e8b01a Start micropost create and destroy
s 1136191 Add functionality for creating posts
s e30ae46 Display a user's feed
s 2f0d0ad Add deletion of microposts
s 93a58fe Test with integration create and delete of micropost
s b13667d Add Packages required for images
s 48b6ecd Add base picture uploader
s 7c507ad Add picture to micropost
s 5827d6e Add images to microposts
s eefeb9d Add uless files to the .gitignore
s a97bf3b Add server side validation for image format and size
s 982577f Add client validation for file format and size
s 24a3d0e Add Amazon S3 as production storage

**Pull request merged**
